# Tensor의 선언
torch.Tensor(크기)

위 함수를 사용하면 초기화 되지 않은 Tensor를 생성할 수 있습니다.

In [9]:
import torch
x=torch.Tensor(3)
x

tensor([-5.2541e+30,  3.0931e-41, -5.2514e+30])

In [10]:
x2=torch.Tensor(3,3)
x2

tensor([[4.0396e-34, 4.5640e-41, 4.0396e-34],
        [4.5640e-41, 4.4842e-44, 0.0000e+00],
        [4.4842e-44, 0.0000e+00, 0.0000e+00]])

Tensor의 random 선언

a = torch.rand(3,3)    
rand를 통한 a는 0에서 1사이의 uniform distribution random 값으로 선언

a = torch.randn(3,3)    
randn을 통한 a는 평균이 0이고 분산이 1인 normal distribution random값으로 선언

## Numpy 에서  Tensor로

In [11]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
b=torch.Tensor(a)
print(b)

[1 2 3 4]
tensor([1., 2., 3., 4.])


## Tensor에서 Numpy로

In [13]:
a = torch.rand(3,3)
print(a)
b = a.numpy()
print(b)

tensor([[0.8946, 0.5471, 0.3681],
        [0.6538, 0.9443, 0.9298],
        [0.9285, 0.9125, 0.7451]])
[[0.8946213  0.5470751  0.36805457]
 [0.65379745 0.9443485  0.9298206 ]
 [0.9284621  0.9125066  0.7451272 ]]


## Tensor의 형태 변환(view)

In [15]:
a = torch.rand(3,3)
print(a)
a = a.view(1,1,3,3)
a

tensor([[0.8955, 0.1011, 0.5072],
        [0.0241, 0.8527, 0.6405],
        [0.5084, 0.7321, 0.0048]])


tensor([[[[0.8955, 0.1011, 0.5072],
          [0.0241, 0.8527, 0.6405],
          [0.5084, 0.7321, 0.0048]]]])

## Tensor 합치기

torch.cat((Tensor_A, Tensor_B), dim)

Tensor_A 와 Tensor_B를 dim에 맞춰서 합쳐 줍니다.

In [17]:
a = torch.randn(1,1,3,3)
b = torch.randn(1,1,3,3)
c = torch.cat((a,b),0)
c

tensor([[[[-0.6066,  0.6303,  0.2503],
          [ 0.4859,  0.7599,  0.0350],
          [-0.1078, -0.9628,  2.0198]]],


        [[[-0.0389,  0.7441,  0.5288],
          [ 1.6967,  0.5889,  2.7970],
          [-0.1318,  0.7324, -0.6400]]]])

## Tensor 계산을 GPU로

In [18]:
x = torch.rand(3,3)
y = torch.rand(3,3)
if torch.cuda.is_available():
    x=x.cuda()
    y=y.cuda()
    sum=x+y
sum

tensor([[1.0101, 0.5979, 1.4648],
        [1.4333, 0.8605, 0.6833],
        [1.2005, 1.2691, 1.8315]], device='cuda:0')

## 그 외

In [19]:
a = torch.rand(3,3)
print(a)
print(a.mean()) # Tensor a의 평균
a.sum() # Tensor a의 원소 합

tensor([[0.9737, 0.6029, 0.0629],
        [0.5815, 0.5424, 0.1903],
        [0.7287, 0.8486, 0.9953]])
tensor(0.6140)


tensor(5.5261)

## 다양한 함수
http://pytorch.org/docs/master/tensors.html