# 3x3 Conv2d

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable

In [2]:
input = torch.ones(1,1,3,3)
filter = torch.ones(1,1,3,3)

In [3]:
input = Variable(input, requires_grad=True)
print(input)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)


In [4]:
filter = Variable(filter)

In [5]:
out = F.conv2d(input,filter)

In [6]:
print(out)

tensor([[[[9.]]]], grad_fn=<MkldnnConvolutionBackward>)


In [7]:
out.backward()

In [8]:
print(out.grad_fn)

In [9]:
print(input.grad)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])
