# Autograd : automatic differentiation

Autograd를 사용하면 backprop을 위한 미분 값을 자동으로 게산해줌

자동 계산을 위해 사용하는 변수가 torch.autograd에 있는 Variable임.

In [1]:
import torch
from torch.autograd import Variable
a = torch.rand(5)
a = Variable(a)

![image.png](1.png)

In [2]:
# 2x2의 1만 있는 행렬로 선언
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [3]:
# requires_grad -> gradient 값이 필요하다는 뜻
a = Variable(a, requires_grad=True)
print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
print(torch.__version__)

1.6.0


In [5]:
print(a.data)
print(a.grad)
print(a.grad_fn)

tensor([[1., 1.],
        [1., 1.]])
None
None


In [6]:
b=a+2
print(b)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [7]:
c=b**2
print(c)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)


In [8]:
out = c.sum()
print(out)

tensor(36., grad_fn=<SumBackward0>)


In [9]:
print(out)
out.backward()

tensor(36., grad_fn=<SumBackward0>)


In [10]:
print(a.data)
print(a.grad)
print(a.grad_fn)

tensor([[1., 1.],
        [1., 1.]])
tensor([[6., 6.],
        [6., 6.]])
None


In [11]:
print(b.data)
print(b.grad)
print(b.grad_fn)

tensor([[3., 3.],
        [3., 3.]])
None


<ipython-input-11-7222c1aec66c>:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(b.grad)


In [12]:
print(c.data)
print(c.grad)
print(c.grad_fn)

tensor([[9., 9.],
        [9., 9.]])
None


<ipython-input-12-f6ca42a4f63f>:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(c.grad)


In [13]:
print(out.data)
print(out.grad)
print(out.grad_fn)

tensor(36.)
None


<ipython-input-13-85e75c577388>:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(out.grad)


In [14]:
x=torch.ones(3)
x=Variable(x, requires_grad=True)
y=(x**2)
z=y*3
print(z)
grad=torch.Tensor([0.1,1,10])
z.backward(grad)

tensor([3., 3., 3.], grad_fn=<MulBackward0>)


In [16]:
print(x.data)
print(x.grad)
print(x.grad_fn)
# z = 3 x X^2
# dz/dx = 3*2*x , 여기서 x는 1이기 때문에 6 이 되어야 하는데
# grad=torch.Tensor([0.1,1,10]) 의 값으로 인해 0.6, 6 , 60 이 됨

tensor([1., 1., 1.])
tensor([ 0.6000,  6.0000, 60.0000])
None
